sudo: required
language: python
python:
  - "2.7" 

install:
  - ./.install-htslib.sh
  - pip install cffi nose coverage coveralls codecov sphinx
  - python setup.py develop

script:
  - cd docs && make htmls && cd ..
  - coverage run --source=hts setup.py nosetests

after_success:
  - codecov
    #- coveralls
